# -*- coding: utf-8 -*-
"""Homework_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2yZTu0Rj2uDAzKhbtu9wBH7aPZTmOfI

# Theory Questions

## Question 1: CPU and Binary Fundamentals
"""

def theory_cpu_binary():
    """
    ANSWER THE FOLLOWING THEORY QUESTIONS:

    1. Explain in 2-3 sentences how a CPU processes instructions using only 0s and 1s.

    2. Why do we use binary (base-2) instead of decimal (base-10) in computers?

    3. How does the CPU differentiate between the number 65 and the character 'A'
       if they have the same binary representation?

    Return your answers as a list of 3 strings.
    """
    answer1 = (
        "The CPU processes instructions as binary machine code, where 0s and 1s "
        "represent electrical signals being off or on. Each instruction is fetched "
        "from memory, decoded by the control unit, and executed by the arithmetic logic unit (ALU)."
    )

    answer2 = (
        "Computers use binary because electronic components like transistors naturally "
        "operate in two stable states — on (1) and off (0). This makes binary systems "
        "simpler, faster, and more reliable than multi-level (e.g., decimal) systems."
    )

    answer3 = (
        "The CPU itself doesn’t inherently know if 01000001 represents a number or a character. "
        "The interpretation depends on context — programming languages and software define "
        "how to treat that binary pattern, such as 65 for a number or 'A' for a character."
    )
    return [answer1, answer2, answer3]

# This function tests if answers exist (not content)
def test_theory_answers():
    answers = theory_cpu_binary()
    assert len(answers) == 3, "Must provide 3 answers"
    assert all(isinstance(ans, str) for ans in answers), "All answers must be strings"
    assert all(len(ans.strip()) > 0 for ans in answers), "All answers must be non-empty"
    print("Theory Question 1 format passed!")

test_theory_answers()

"""##Question 2: Data Types Memory Usage"""

def theory_data_types():
    """
    ANSWER THE FOLLOWING THEORY QUESTIONS:

    1. How many bits are typically used to store:
       - An integer in Python?
       - A single character?
       - A boolean value?

    2. Explain why a list can contain different data types but arrays in low-level
       languages usually cannot.

    3. What happens at the binary level when you convert a string to uppercase?

    Return your answers as a dictionary.
    """
    answers ={
        "question1": (
            "Python integers are of arbitrary size (their bit length grows as needed), "
            "but a typical fixed-size integer in C or most systems uses 32 bits. "
            "A single character (like in ASCII) uses 8 bits, and a boolean value uses 1 bit, "
            "though Python internally stores it as a full byte (8 bits)."
            ),

        "question2": (
            "A Python list stores references (pointers) to objects in memory, "
            "allowing each element to be of a different data type. "
            "In contrast, arrays in low-level languages like C must store data of the same type "
            "in contiguous memory for efficient access and predictable memory layout."
        ),

      "question3": (
            "At the binary level, converting a lowercase letter to uppercase changes certain bits "
            "in its ASCII code. Specifically, the 6th bit is flipped from 1 to 0, "
            "reducing the ASCII value by 32 and producing the uppercase version of the letter."
        )
    }
    return answers

# Test structure only
def test_theory_data_types():
    answers = theory_data_types()
    assert isinstance(answers, dict), "Answers must be in dictionary format"
    assert len(answers) == 3, "Must answer all 3 questions"
    assert all(key in answers for key in ["question1", "question2", "question3"])
    print("Theory Question 2 format passed!")

test_theory_data_types()

"""##Question 3: From Hardware to Programming"""

def theory_hardware_to_code():
    """
    EXPLAIN THE JOURNEY in 4-5 sentences:

    Describe the complete process from when you type a letter on your keyboard
    to how that character gets stored in memory as binary, and then how Python
    interprets it as a string data type.

    Include: keyboard input, ASCII conversion, memory storage, and Python's
    string object creation.
    """
    explanation = """
    Your detailed explanation here...

    1. First, when I press a key...
    2. Then, the keyboard controller...
    3. The CPU processes...
    4. Finally, Python...
    """
    return explanation

def test_theory_journey():
    explanation = theory_hardware_to_code()
    assert isinstance(explanation, str), "Answer must be a string"
    assert len(explanation.strip()) > 100, "Provide a detailed explanation (min 100 characters)"
    # Count sentences roughly by counting periods
    sentences = explanation.count('.') + explanation.count('!') + explanation.count('?')
    assert sentences >= 3, "Should have at least 3-4 sentences"
    print("Theory Question 3 format passed!")

test_theory_journey()

"""# Coding Questions

These questions, Q4 - Q20 cover:

* Low-level concepts: Binary conversion, ASCII, memory representation

* Data types: Numbers, strings, lists and their operations

* Practical applications: Type conversion, string/list manipulation

* Creative thinking: Students create their own problems

* Advanced challenges: Bit-level operations and encryption

Each question includes assertion tests so You can immediately verify Your solutions!

#Numerical Operations

##Question 4: Rectangle Area
"""

def rectangle_area(length, width):
    """
    Calculate the area of a rectangle given its length and width.
    Example: (5, 3) -> 15, (10.5, 2) -> 21.0
    """
    # Multiply length and width to get the area
    return length * width

# Test cases
assert rectangle_area(5, 3) == 15
assert rectangle_area(10.5, 2) == 21.0
assert rectangle_area(0, 10) == 0
assert rectangle_area(7, 7) == 49
print("Question 4 passed!")

"""##Question 5: Celsius to Fahrenheit"""

def celsius_to_fahrenheit(celsius):
    """
    Convert temperature from Celsius to Fahrenheit.
    Formula: Fahrenheit = (Celsius * 9/5) + 32
    Example: (0) -> 32, (100) -> 212, (37) -> 98.6
    """
    # Apply the conversion formula
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

# Test cases
assert celsius_to_fahrenheit(0) == 32
assert celsius_to_fahrenheit(100) == 212
assert celsius_to_fahrenheit(37) == 98.6
assert celsius_to_fahrenheit(-40) == -40
print("Question 5 passed!")

"""#Getting Input

##Question 6: 100th Birthday Calculator
"""

def calculate_100th_year(name, age):
    """
    Calculate the year when a person will turn 100 years old.
    Example: ("Alice", 25) -> "Hello Alice! You will turn 100 years old in 2099."
    Note: Use current year 2024 for calculations.
    """
    current_year = 2024
    years_left = 100 - age
    hundredth_year = current_year + years_left
    return f"Hello {name}! You will turn 100 years old in {hundredth_year}."

# Test cases
assert calculate_100th_year("Alice", 25) == "Hello Alice! You will turn 100 years old in 2099."
assert calculate_100th_year("Bob", 50) == "Hello Bob! You will turn 100 years old in 2074."
assert calculate_100th_year("Charlie", 0) == "Hello Charlie! You will turn 100 years old in 2124."
print("Question 6 passed!")

"""##Question 7: Basic Calculator"""

def basic_calculator(num1, num2):
    """
    Perform basic arithmetic operations on two numbers.
    Return a tuple containing: (sum, difference, product, quotient)
    Handle division by zero by returning "undefined" for quotient.
    Example: (10, 5) -> (15, 5, 50, 2), (10, 0) -> (10, 10, 0, "undefined")
    """
    sum_result = num1 + num2
    diff_result = num1 - num2
    product_result = num1 * num2
    quotient_result = num1 / num2 if num2 != 0 else "undefined"

    return (sum_result, diff_result, product_result, quotient_result)

# Test cases
assert basic_calculator(10, 5) == (15, 5, 50, 2)
assert basic_calculator(10, 0) == (10, 10, 0, "undefined")
assert basic_calculator(7, 3) == (10, 4, 21, 7/3)
assert basic_calculator(-5, 2) == (-3, -7, -10, -2.5)
print("Question 7 passed!")

"""#Numeric Types

##Question 8: Circle Area
"""

def circle_area(radius):
    """
    Calculate the area of a circle given its radius.
    Formula: Area = π * radius²
    Use math.pi for the value of π
    Example: (5) -> 78.5398..., (0) -> 0, (1) -> 3.14159...
    """
    # Use the formula for the area of a circle
    area = math.pi * (radius ** 2)
    return area

# Test cases
import math
assert abs(circle_area(5) - 78.5398) < 0.001
assert circle_area(0) == 0
assert abs(circle_area(1) - 3.14159) < 0.001
assert abs(circle_area(10) - 314.159) < 0.1
print("Question 8 passed!")

"""#Augmented Assignments

##Question 9: To-Do List Tracker
"""

def todo_list_tracker(initial_tasks, new_tasks_list):
    """
    Track completed tasks using augmented assignments.
    Start with initial_tasks completed, then add each value from new_tasks_list.
    Return the final number of completed tasks.
    Example: (0, [1, 3, 2]) -> 6, (5, [1, 1, 1]) -> 8
    """
     # Add each new task count using augmented assignment
    for task in new_tasks_list:
        initial_tasks += task
    return initial_tasks


# Test cases
assert todo_list_tracker(0, [1, 3, 2]) == 6
assert todo_list_tracker(5, [1, 1, 1]) == 8
assert todo_list_tracker(10, []) == 10
assert todo_list_tracker(0, [5, -2, 3]) == 6  # Negative means removed tasks
print("Question 9 passed!")

"""##Question 10: Binary Conversion

Hint - You can use also math operations or use built-in functions.
"""

def decimal_to_binary(decimal_num):
    """
    Convert a decimal number to binary representation.
    Example: 5 -> '101', 10 -> '1010'
    """
    if decimal_num == 0:
        return '0'

    binary_digits = []
    while decimal_num > 0:
        remainder = decimal_num % 2
        binary_digits.insert(0, str(remainder))
        decimal_num //= 2

    return ''.join(binary_digits)


# Test cases
assert decimal_to_binary(5) == '101'
assert decimal_to_binary(10) == '1010'
assert decimal_to_binary(0) == '0'
assert decimal_to_binary(255) == '11111111'
print("Question 10 passed!")

"""##Question 11: ASCII Representation"""

def char_to_ascii_binary(char):
    """
    Convert a character to its ASCII value in binary.
    Example: 'A' -> '01000001', 'a' -> '01100001'
    """
    ascii_value = ord(char)               # Get ASCII integer value
    binary_str = format(ascii_value, '08b')  # Convert to 8-bit binary string
    return binary_str


# Test cases
assert char_to_ascii_binary('A') == '01000001'
assert char_to_ascii_binary('a') == '01100001'
assert char_to_ascii_binary('0') == '00110000'
print("Question 11 passed!")

"""##Question 12: Binary to Decimal"""

def binary_to_decimal(binary_str):
    """
    Convert binary string to decimal number.
    Example: '101' -> 5, '1101' -> 13
    """
def binary_to_decimal(binary_str):
    return int(binary_str, 2)


# Test cases
assert binary_to_decimal('101') == 5
assert binary_to_decimal('1101') == 13
assert binary_to_decimal('0') == 0
assert binary_to_decimal('11111111') == 255
print("Question 12 passed!")

"""##Question 13: Memory Representation"""

def demonstrate_same_bits():
    """
    Show that 'A' and 65 have the same bit pattern in memory.
    Return a List: [binary_of_A, binary_of_65, are_they_same]
    """
    # Convert character 'A' to ASCII value, then to binary
    binary_of_A = format(ord('A'), '08b')  # '01000001'

    # Convert integer 65 to binary
    binary_of_65 = format(65, '08b')       # '01000001'

    # Check if they are the same
    are_they_same = binary_of_A == binary_of_65

    return [binary_of_A, binary_of_65, are_they_same]

# Test cases
result = demonstrate_same_bits()
assert result[0] == result[1]  # Same binary representation
assert result[2] == True       # They are the same
print("Question 13 passed!")

"""##Question 14: Number Type Identification

Hint - Try using math operations and a list to choose between "int" and "float".

    number = 5.0`

    whole_part = number // 1`       # 5.0

    fraction = number - whole_part`  # 0.0

    fraction == 0 → 'int'

    List = ['int', 'float']

    List[0] → 'int'
"""

def identify_number_type(number):
    """
    Identify if number is best stored as int or float.
    Return "int" for whole numbers, "float" for decimals.
    """
    types_list = ['int', 'float']
    whole_part = number // 1
    fraction = number - whole_part
    # fraction == 0 means whole number
    return types_list[0] if fraction == 0 else types_list[1]

# Test cases
assert identify_number_type(5) == "int"
assert identify_number_type(5.0) == "int"
assert identify_number_type(3.14) == "float"
assert identify_number_type(-10) == "int"
print("Question 14 passed!")

"""##Question 15: String Manipulation

vowel_count = 0
    vowel_count += (text[0] in vowels) * 1
"""

def string_operations(text):
    """
    Perform: uppercase, reverse, and count vowels.
    Return List: [uppercase, reversed, vowel_count]
    """
    vowels = "AEIOUaeiou"

    # Convert to uppercase
    upper_text = text.upper()

    # Reverse the string
    reversed_text = text[::-1]

    # Count vowels
    vowel_count = sum((char in vowels) * 1 for char in text)

    return [upper_text, reversed_text, vowel_count]


# Test cases
assert string_operations("Hello") == ["HELLO", "olleH", 2]
assert string_operations("Python") == ["PYTHON", "nohtyP", 1]
assert string_operations("AEIOU") == ["AEIOU", "UOIEA", 5]
print("Question 15 passed!")

"""##Question 16: List Operations"""

def list_manipulation(numbers):
    """
    Perform: sort, remove duplicates, find max/min.
    Return tuple: (sorted_list, unique_list, max_value, min_value)
    """
    # Sorted list (ascending)
    sorted_list = sorted(numbers)

    # Unique list (preserve original order)
    unique_list = []
    for num in numbers:
        if num not in unique_list:
            unique_list.append(num)

# Test cases
assert list_manipulation([3, 1, 4, 1, 5, 9]) == ([1, 1, 3, 4, 5, 9], [3, 1, 4, 5, 9], 9, 1)
assert list_manipulation([5, 5, 5]) == ([5, 5, 5], [5], 5, 5)
print("Question 16 passed!")

"""##Question 17: Binary String Operations"""

def binary_string_manipulation(binary_str):
    """
    Take binary string, convert to decimal, then back to binary.
    Also count 1s and 0s in original string.
    Return List: [decimal_value, new_binary, ones_count, zeros_count]
    """
    decimal_value = binary_to_decimal(binary_str)    # We use Question 7: Binary to Decimal function here
    new_binary = decimal_to_binary(decimal_value)    # We use Question 4: Binary Conversion function here
def binary_string_manipulation(binary_str):
    decimal_value = int(binary_str, 2)
    new_binary = bin(decimal_value)[2:]
    ones_count = binary_str.count('1')
    zeros_count = binary_str.count('0')
    return [decimal_value, new_binary, ones_count, zeros_count]

# Test cases
assert binary_string_manipulation("1010") == [10, '1010', 2, 2]
assert binary_string_manipulation("1111") == [15, '1111', 4, 0]
print("Question 17 passed!")

"""##Question 18: Data Type Converter

Hint

1) Think about what you already know:

    * chr(number) → gives a character

    * ord(character) → gives ASCII number

    * format(number, '08b') → gives binary string

    * // 1 → removes decimal part of a float

2) Use Boolean math instead of if/else:

    * True * something = something

    * False * something = 0 or ''

3) Combine the results in a list or string and select the right one based on target_type.

    * Try handling each conversion separately using only math operations, strings, and lists, then pick the one that matches target_type using Boolean multiplication.
"""

def data_type_converter(value, target_type):
    """
    Convert value to target data type.
    target_type can be: 'int', 'float', 'str', 'binary'
    Example: (65, 'str') -> 'A', ('A', 'binary') -> '01000001'
    """
    # Your code here
    pass

# Test cases
assert data_type_converter(65, 'str') == 'A'
assert data_type_converter('A', 'binary') == '01000001'
assert data_type_converter('101', 'int') == 5
assert data_type_converter(3.14, 'int') == 3
print("Question 18 passed!")

"""# Additional Creative Question

## Question 19: Create Your Own
"""

def create_your_own_question():
    """
    CREATE YOUR OWN QUESTION:
    Design a function that demonstrates an interesting concept
    from this week's classes (binary, data types, etc.)

    Write the question description here:
    [Student writes their own question]

    Then implement the solution and test cases.
    """
    # Student writes their question and solution
    pass

# Student writes their own test cases
# assert ...