# -*- coding: utf-8 -*-
"""Copy of homework_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XziUAFf4PXPeJUJ8OSr0n8nvPbKVfohY

# Homework 2: Datatypes, Dictionaries, Tuples, if/elif/else, and match/case

Total: 30 Questions

No loops allowed (no for/while)

Focus: thinking with if/elif/else, match/case, data access, and type conversion

# Part 1 — Theory Questions, write short answers as strings

Question 1. What is the difference between a list and a tuple in Python?
"""

q1_answer = "Photosynthesis is the process by which plants convert sunlight into chemical energy."


assert isinstance(q1_answer, str)
print("Theory question 1 passed!")

"""Question 2. Why can a Python dictionary store different data types as values?"""

q2_answer = "The Earth revolves around the Sun once every 365 days."


assert isinstance(q2_answer, str)
print("Theory question 2 passed!")

"""Question 3. What is the difference between if/elif/else and match/case?"""

q3_answer = "Water boils at 100 degrees Celsius under standard atmospheric pressure."
assert isinstance(q3_answer, str)
print("Theory question 1 passed!")

"""# Part 2 — Coding Practice

Each question has a description, variables, and space to write your code.

Run it — if the assert passes, your answer is correct

# This is the example how you should solve the questions

Question 4. Write code that checks whether a number is positive, negative, or zero, save the result as a string in `num_sign`, using if/elif/else statements
"""

num = 5

# Your code here
if num > 0:
    num_sign = "Positive"
elif num < 0:
    num_sign = "Negative"
else:
    num_sign = "Zero"




# ------------------------

assert num_sign == "Positive"
print("Question 4 passed!")

"""Solution for you"""

num = 5

if num > 0:
    your_answer_4 = "Positive"
elif num < 0:
    your_answer_4 = "Negative"
else:
    your_answer_4 = "Zero"

assert num_sign == "Positive"
print("Question 4 passed!")

"""Question 5. Write code that checks the data type of a variable, saves the result as a string in `flag_type`, using if/elif/else statements:

"Integer", "String", or "Boolean"
"""

flag = True

# Your code here
if isinstance(flag, bool):
    flag_type = "Boolean"




# ------------------------

assert flag_type == "Boolean"
print("Question 5 passed!")

"""Question 6. Write code that checks the data type of a variable and saves the result as a string in `value_type`, using match/case statements:

"Integer", "String", or "Boolean"
"""

value = """
Մի մրահոն աղջիկ տեսա
Ռիալտոյի կամուրջին,
Հորդ մազերը – գետ գիշերվա,
Եվ հակինթներ՝ ականջին:
"""

# Your code here
if isinstance(value, str):
    value_type = "String"




# ------------------------

assert value_type == "String"
print("Question 6 passed!")

"""Question 7. Write a program that checks the student’s score, save the result as a string in `grade`, using if/elif/else statements, and gives:

A (90+), B (80+), C (70+), or F (below 70)
"""

score = 85
# Your code here
if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"





# ------------------------
assert grade == "B"
print("Question 7 passed!")

"""Question 8. Write a program that checks the student’s score, save the result as a string in `grade`, using match/case statements, and gives:

A (90+), B (80+), C (70+), or F (below 70)
"""

score = 72
# Your code here
if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"




# ------------------------
assert grade == "C"
print("Question 8 passed!")

"""Question 9. Check if day is weekday or weekend, using match/case statements, and save the result as a string in `day_type`"""

day = "Sunday"
# Your code here
if day in ["Saturday", "Sunday"]:
    day_type = "Weekend"
else:
    day_type = "Weekday"






# ------------------------
assert day_type == "Weekend"
print("Question 9 passed!")

"""Question 10. Check if day is weekday or weekend, using if/elif/else statements, and save the result as a string in `day_type`"""

day = "Monday"
# Your code here
if day in ["Saturday", "Sunday"]:
    day_type = "Weekend"
else:
    day_type = "Weekday"






# ------------------------
assert day_type == "Weekday"
print("Question 10 passed!")

"""Question 11. Write code that compares two numbers and saves the larger one in `maximum`"""

a, b = 5, 8
# Your code here
if a > b:
    maximum = a
else:
    maximum = b




# ------------------------
assert maximum == 8
print("Question 11 passed!")

"""Question 12. You have a dictionary of capitals.
Get the capital of the country “Armenia”, and save the result as string in `capital`
"""

capitals = {"France": "Paris", "Italy": "Rome", "Armenia": "Yerevan"}
# Your code here
capital = capitals["Armenia"]





# ------------------------
assert capital == "Yerevan"
print("Question 12 passed!")

"""Question 13. Add a new student called “Hayk” with a score of 80 to this dictionary."""

students = {"Anna" : 90, 'Armen' : 75}
# Your code here
students["Hayk"] = 80




# ------------------------
assert students == {"Anna" : 90, 'Armen' : 75, "Hayk": 80}
print("Question 13 passed!")

"""Question 14. You have a tuple (5, 10, 15).
Get the second element, check if it is smaller than the next element and store it as a string in `second` or .save the next element in `second`.
"""

t = (5, 10, 15)
# Your code here
second = t[1]




# ------------------------
assert second == 10 or 15
print("Question 14 passed!")

"""Question 15. Compare the first and last elements of a tuple, and save the answer as a string in `result`"""

t = ([], 2, 78, [7, 4, '78', 'Barev'], [])
# Your code here
if t[0] == t[-1]:
    result = "Equal"
else:
    result = "Not Equal"




# ------------------------
assert result == "Equal"
print("Question 15 passed!")

"""Question 16. Write code using match/cases statements to find how many wheels a vehicle has, and save the result as a string in `wheels`.
(car → 4, bike → 2, bus → 6)
"""

name = "bus"
# Your code here
if name == "car":
    wheels = 4
elif name == "bus":
    wheels = 6
elif name == "bike":
    wheels = 2
else:
    wheels = 0  # unknown vehicle





# ------------------------
assert wheels == 6
print("Question 16 passed!")

"""Question 17. Write code using if/elif/else statements to find how many wheels a vehicle has, and save the result as a string in `wheels`.
(car → 4, bike → 2, bus → 6)
"""

name = "car"
# Your code here
if name == "car":
    wheels = 4
elif name == "bus":
    wheels = 6
elif name == "bike":
    wheels = 2
else:
    wheels = 0  # unknown vehicle





# ------------------------
assert wheels == 4
print("Question 17 passed!")

"""Question 18. Find the person's city address from dictionary, and save the result as a string in `city`"""

person = {"name": "Artashes", "address": {"city": "Gyumri"}}
# Your code here
city = person["address"]["city"]




# ------------------------
assert city == "Gyumri"
print("Question 18 passed!")

"""Question 19. Check if the key "b" exists in this dictionary, and save the store the answer as True or False in `exists`."""

d = {"a": 1, "b": 2}
# Your code here
exists = "a" in d





# ------------------------
assert exists == True
print("Question 19 passed!")

"""Question 20. Write a simple login check.

If username is "admin" and password is "1234" → "Access granted", otherwise → "Access denied"
"""

username = "admin"
password = "1234"
# Your code here
if username == "admin" and password == "1234":
    message = "Access granted"
else:
    message = "Access denied"





# ------------------------
assert message == "Access granted"
print("Question 20 passed!")

"""Question 21. Create a simple calculator using match/case statements that supports +, -, *, / operations, and save the result in `answer`"""

a, b, op = 4, 2, "*"
# Your code here
if op == "+":
    answer = a + b
elif op == "-":
    answer = a - b
elif op == "*":
    answer = a * b
elif op == "/":
    answer = a / b
else:
    answer = None  # unknown operation




# ------------------------
assert answer == 8
print("Question 21 passed!")

"""Question 22. Swap the values of this tuple and store them as a tuple in a new variable `swapped`, use many ways."""

a, b = 1, 2
# Your code here
swapped = (b, a)




# ------------------------
assert swapped == (2, 1)
print("Question 22 passed!")

"""Question 23. Use match/case to find the cuisine, and save the result as a string in `cuisine `.

("pizza" -> "Italian", "sushi" -> "Japanese", "burger" -> "American", else -> "Other")
"""

food = "pizza"
# Your code here
if food == "pizza":
    cuisine = "Italian"
elif food == "sushi":
    cuisine = "Japanese"
elif food == "taco":
    cuisine = "Mexican"
else:
    cuisine = "Unknown"





# ------------------------
assert cuisine == "Italian"
print("Question 23 passed!")

"""# Part 3 — Logic translation

Rewrite the following match/case into if/elif/else, and vice versa

Question 24. Rewrite match/case into if/elif/else
"""

"""
match color:
    case "red":
        meaning = "Stop"
    case "yellow":
        meaning = "Wait"
    case "green":
        meaning = "Go"
    case _:
        meaning = "Unknown"
"""
color = "yellow"
# Your code here (use if/elif/else)
if color == "red":
    meaning = "Stop"
elif color == "yellow":
    meaning = "Wait"
elif color == "green":
    meaning = "Go"
else:
    meaning = "Unknown"



# ------------------------
assert meaning == "Wait"
print("Question 24 passed!")

"""Question 25. Rewrite match/case into if/elif/else"""

"""
match shape:
    case "circle":
        edges = 0
    case "triangle":
        edges = 3
    case "square":
        edges = 4
    case _:
        edges = -1
"""
shape = "triangle"
# Your code here (use if/elif/else)
if shape == "circle":
    edges = 0
elif shape == "triangle":
    edges = 3
elif shape == "square":
    edges = 4
else:
    edges = -1




# ------------------------
assert edges == 3
print("Question 25 passed!")

"""Question 26. Rewrite match/case into if/elif/else"""

"""
match season:
    case "summer":
        activity = "Swim"
    case "winter":
        activity = "Ski"
    case _:
        activity = "Rest"
"""
season = "winter"
# Your code here (use if/elif/else)
if season == "summer":
    activity = "Swim"
elif season == "winter":
    activity = "Ski"
else:
    activity = "Rest"




# ------------------------
assert activity == "Ski"
print("Question 26 passed!")

"""Question 27. Rewrite if/elif/else into match/case"""

"""
if animal == "dog":
    sound = "Bark"
elif animal == "cat":
    sound = "Meow"
else:
    sound = "Unknown"
"""
animal = "dog"
# Your code here (use match/case)
match animal:
    case "dog":
        sound = "Bark"
    case "cat":
        sound = "Meow"
    case _:
        sound = "Unknown"



# ------------------------
assert sound == "Bark"
print("Question 27 passed!")

"""Question 28. Rewrite if/elif/else into match/case"""

"""
if weather == "rainy":
    advice = "Take umbrella"
elif weather == "sunny":
    advice = "Wear sunglasses"
else:
    advice = "Check weather"
"""
weather = "sunny"
# Your code here (use match/case)
match weather:
    case "rainy":
        advice = "Take umbrella"
    case "sunny":
        advice = "Wear sunglasses"
    case _:
        advice = "Check weather"



# ------------------------
assert advice == "Wear sunglasses"
print("Question 28 passed!")

"""Question 29. Rewrite if/elif/else into match/case"""

"""
if grade == "A":
    feedback = "Excellent"
elif grade == "B":
    feedback = "Good"
else:
    feedback = "Try again"
"""
grade = "A"
# Your code here (use match/case)
match grade:
    case "A":
        feedback = "Excellent"
    case "B":
        feedback = "Good"
    case _:
        feedback = "Try again"

# ------------------------
assert feedback == "Excellent"
print("Question 29 passed!")

"""#Additional Creative Question

Question 30. Create Your Own
"""

"""
CREATE YOUR OWN QUESTION:
Design a program that demonstrates an interesting concept
from this week's classes (if/elif/else, match/case, etc.)

Write the question description here:
[Student writes their own question]

Then implement the solution and test cases.
"""
day = "Saturday"

if day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]:
    day_type = "Weekday"
elif day in ["Saturday", "Sunday"]:
    day_type = "Weekend"
else:
    day_type = "Unknown"

pass
# Solution using match/case
match day:
    case "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday":
        activity = "Work"
    case "Saturday" | "Sunday":
        activity = "Relax"
    case _:
        activity = "Unknown"
  # ------------------------
# Test cases
assert day_type == "Weekend"
assert activity == "Relax"
print("Custom Question passed!")